Algoritmo "consumo"
// Curso de Algoritmos e Lógica de Programação
// Professor: Nelio Alves
// Estrutura Sequencial
// Lista de Exercícios
// Github: @pythanx
Var

   distancia, totalCombustivel, consumo: real

Inicio
    escreval("Distância percorrida: ")
    leia(distancia)
    escreval("Combustível gasto: ")
    leia(totalCombustivel)
    
    consumo <- distancia / totalCombustivel
    
    escreval("Consumo médio = ", consumo:8:3)
      


Fimalgoritmo
